apiVersion: v1
kind: Pod
metadata:
  name: scraper-test-pod
  namespace: ml-scraper
  labels:
    app: scraper
    job_name: scraper-test-1
spec:
  containers:
    - name: scraper
      image: busybox
      command: ["sh", "-c", "for i in 1 2 3 4 5; do echo \"[INFO] Scrapeando producto iphone pagina $i\"; sleep 2; done"]
  restartPolicy: Never
