---
# cronjob.yaml — TP2 - PARTE 3 - HIT 5: agrega NODE_IP + envFrom otel-collector-endpoint
# Diferencia respecto al TP 1 - HIT 8:
#   + env NODE_IP (fieldRef status.hostIP) para que el ConfigMap pueda
#     expandir $(NODE_IP) en OTEL_EXPORTER_OTLP_ENDPOINT.
#   + envFrom otel-collector-endpoint: inyecta las variables OTel al container.
#   + imagen actualizada a ml-scraper:otel-v1
apiVersion: batch/v1
kind: CronJob
metadata:
  name: scraper-hourly
  namespace: ml-scraper
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: 2
      template:
        metadata:
          labels:
            app: scraper
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: wait-for-postgres
              image: busybox:1.36
              command:
                - sh
                - -c
                - |
                  until nc -z postgres 5432; do
                    echo "Esperando PostgreSQL..."; sleep 3;
                  done
                  echo "PostgreSQL listo."
          containers:
            - name: scraper
              image: ml-scraper:otel-v1      # <-- imagen nueva con OTel
              imagePullPolicy: IfNotPresent
              env:
                # NODE_IP: IP del nodo donde corre este Pod.
                # Usado por el ConfigMap para expandir OTEL_EXPORTER_OTLP_ENDPOINT.
                - name: NODE_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: postgres-secret
                      key: POSTGRES_PASSWORD
              envFrom:
                # Config base del scraper (BROWSER, HEADLESS, PRODUCTS, etc.)
                - configMapRef:
                    name: scraper-config
                # Variables OTel (OTEL_EXPORTER_OTLP_ENDPOINT, OTEL_SERVICE_NAME, etc.)
                - configMapRef:
                    name: scraper-otlp-config 
              volumeMounts:
                - name: output
                  mountPath: /app/output
                - name: screenshots
                  mountPath: /app/screenshots
                - name: dshm
                  mountPath: /dev/shm
          volumes:
            - name: output
              persistentVolumeClaim:
                claimName: scraper-output
            - name: screenshots
              emptyDir: {}
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 512Mi