apiVersion: v1
data:
  OTEL_EXPORTER_OTLP_ENDPOINT: http://agent-collector.otel.svc.cluster.local:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_LOGS_EXPORTER: otlp
  OTEL_SERVICE_NAME: scraper
  OTEL_TRACES_EXPORTER: otlp
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"OTEL_EXPORTER_OTLP_ENDPOINT":"http://agent-collector.otel.svc.cluster.local:4317","OTEL_EXPORTER_OTLP_PROTOCOL":"grpc","OTEL_LOGS_EXPORTER":"otlp","OTEL_SERVICE_NAME":"scraper","OTEL_TRACES_EXPORTER":"otlp"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"scraper-otlp-config","namespace":"ml-scraper"}}
  creationTimestamp: "2026-05-08T21:31:38Z"
  name: scraper-otlp-config
  namespace: ml-scraper
  resourceVersion: "21098"
  uid: e765bab5-f7fd-4824-a2eb-7abb06f6873b
